// export const TESTIMONIALS = [
//     {
//         name: "Sarah Leeman",
//         role: "Marketing Leader",
//         company: "Mailchimp",
//         companyUrl: "https://mailchimp.com",
//         image: "/images/testimonials/person1.jpg",
//         content: "It's intuitive, functional, easy-to-setup and presents content beautifully.",
//         time: "3:45 PM",
//         date: "Jun 20, 2024",
//     },
//     {
//         name: "Amaya Locosta",
//         role: "Marketing Leader",
//         company: "Mailchimp",
//         companyUrl: "https://mailchimp.com",
//         image: "/images/testimonials/person2.jpg",
//         content: "The platform made our workflow seamless and efficient.",
//         time: "11:10 AM",
//         date: "Jul 2, 2024",
//     },
//     {
//         name: "John Doe",
//         role: "Product Manager",
//         company: "Google",
//         companyUrl: "https://google.com",
//         image: "/images/testimonials/person3.jpg",
//         content: "This tool has transformed the way we manage our projects.",
//         time: "9:30 AM",
//         date: "Aug 15, 2023",
//     },
//     {
//         name: "Emily Johnson",
//         role: "Software Engineer",
//         company: "Microsoft",
//         companyUrl: "https://microsoft.com",
//         image: "/images/testimonials/person4.jpg",
//         content: "A game-changer for our development team, highly recommend!",
//         time: "2:00 PM",
//         date: "Sep 5, 2024",
//     },
//     {
//         name: "Michael Smith",
//         role: "UX Designer",
//         company: "Adobe",
//         companyUrl: "https://adobe.com",
//         image: "/images/testimonials/person1.jpg",
//         content: "The design capabilities are top-notch, making our work so much easier.",
//         time: "4:15 PM",
//         date: "Oct 10, 2024",
//     },
//     {
//         name: "Olivia Brown",
//         role: "Data Analyst",
//         company: "IBM",
//         companyUrl: "https://ibm.com",
//         image: "/images/testimonials/person2.jpg",
//         content: "Incredible insights and analytics, a must-have for any data team.",
//         time: "1:20 PM",
//         date: "Nov 25, 2024",
//     },
// ];


export const TESTIMONIALS = [
  {
    name: "Jake Turner",
    role: "CPO",
    company: "Oak & Pine Co.",
    companyUrl: "https://oakandpineco.com",
    image: "/images/testimonials/person1.jpg",
    content: "We saw steady growth after switching to their ad strategy — no wild promises, just real progress.",
    time: "4:02 PM",
    date: "Jun 14, 2024",
  },
  {
    name: "Lena Rivera",
    role: "Marketing Manager",
    company: "Nuvora Skincare",
    companyUrl: "https://nuvoraskin.com",
    image: "/images/testimonials/person2.jpg",
    content: "Their team helped us restructure our campaigns. Conversions went up without needing to increase spend.",
    time: "10:47 AM",
    date: "Jul 6, 2024",
  },
  {
    name: "Harsh Mehra",
    role: "E-commerce Head",
    company: "Leatherly Goods",
    companyUrl: "https://leatherlygoods.in",
    image: "/images/testimonials/person3.jpg",
    content: "We’d tried running ads before, but it finally clicked with these guys. Clear reporting and no jargon.",
    time: "12:33 PM",
    date: "Aug 10, 2024",
  },
  {
    name: "Tanya Desai",
    role: "Real Estate Consultant",
    company: "BrickNest Realty",
    companyUrl: "https://bricknestrealty.com",
    image: "/images/testimonials/person4.jpg",
    content: "Their lead-gen campaigns actually brought in serious inquiries. It’s been more consistent than anything we’ve tried before.",
    time: "2:18 PM",
    date: "Sep 21, 2024",
  },
  {
    name: "Mark Phillips",
    role: "Creative Director",
    company: "Kindred Studio",
    companyUrl: "https://kindredstudio.co",
    image: "/images/testimonials/person1.jpg",
    content: "The ad visuals were clean and well aligned with our brand tone. Felt like a collaborative effort throughout.",
    time: "11:05 AM",
    date: "Oct 12, 2024",
  },
  {
    name: "Riya Khandelwal",
    role: "Co-Founder",
    company: "Hauswear India",
    companyUrl: "https://hauswear.in",
    image: "/images/testimonials/person2.jpg",
    content: "Not the cheapest, but easily the most accountable agency we've worked with. Worth it for the results.",
    time: "5:09 PM",
    date: "Nov 17, 2024",
  },
];
